# Permite que o H2 seja acessado via navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configura o banco em memória
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=${DB_Username}
spring.datasource.password=${DB_password}

