
# H2 connection
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=${DB_Username}
spring.datasource.password=#${DB_password}
# H2 client
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Show sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#${DB_Username}
#${DB_password}

